#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.M3{1,0,4.9,3
#
pinInterrupt.xm3g: package/cfg/pinInterrupt.xm3g.mak

clean::
	-$(RM) package/cfg/pinInterrupt.xm3g.mak
